
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.openpdf;
import static common.openpdf.openbyId;
import dao.connectionprovider;
import dao.inventoryutils;
import java.io.FileOutputStream;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author GudaT
 */
public class manageorder extends javax.swing.JFrame {

    private int customerpk = 0;
    private int productpk = 0;
    private int finaltotalprice = 0;
    private String orderid = "";

    /**
     * Creates new form manageorder
     */
    public manageorder() {
        initComponents();
        setLocationRelativeTo(null);
    }

    private void clearproductfields() {
        productpk = 0;
        txtproductname.setText("");
        txtproductprice.setText("");
        txtproductdescription.setText("");
        txtorderquantity.setText("");

    }

    public String getUniqueID(String prefix) {
        return prefix + System.nanoTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecustomer = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableproduct = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablecart = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcustomername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcustomermobilenumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcustomeremail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtproductname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtproductprice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtproductdescription = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtorderquantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblfinaltotalprice = new javax.swing.JLabel();
        btnsaveorderdetails = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setText("Manage Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Customer List");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 110, -1, -1));

        tablecustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile Number", "Email"
            }
        ));
        tablecustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablecustomer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 149, 336, 216));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Product List");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 110, -1, -1));

        tableproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name ", "Price", "Quantity", "Discription", "Catagory ID", "Catagory Name"
            }
        ));
        tableproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableproduct);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 149, -1, 216));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Cart");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1069, 110, 37, -1));

        tablecart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Quantity", "Price", "Description", "Sub Total"
            }
        ));
        tablecart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecartMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablecart);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 149, 383, 216));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Selected Customer:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 456, 37, -1));

        txtcustomername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtcustomername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 490, 336, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Mobile Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 531, -1, -1));

        txtcustomermobilenumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtcustomermobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 565, 336, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 614, 37, -1));

        txtcustomeremail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtcustomeremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 648, 336, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Selected Product:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Product Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        txtproductname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtproductname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 452, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Product Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, -1));

        txtproductprice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtproductprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 452, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Product Description");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, -1, -1));

        txtproductdescription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtproductdescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductdescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(txtproductdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 452, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Order Quantity");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, -1, -1));

        txtorderquantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtorderquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorderquantityActionPerformed(evt);
            }
        });
        getContentPane().add(txtorderquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 680, 452, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 720, 452, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Total Amount Rs:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1006, 413, -1, -1));

        lblfinaltotalprice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblfinaltotalprice.setText("00000");
        getContentPane().add(lblfinaltotalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 413, -1, -1));

        btnsaveorderdetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsaveorderdetails.setText("Save Order Details");
        btnsaveorderdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveorderdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnsaveorderdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 490, 383, -1));

        btnreset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 573, 383, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 648, 383, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Orders_background.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 1450, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        txtcustomername.setEditable(false);
        txtcustomermobilenumber.setEditable(false);
        txtcustomeremail.setEditable(false);

        txtproductname.setEditable(false);
        txtproductdescription.setEditable(false);
        txtproductprice.setEditable(false);
        DefaultTableModel model = (DefaultTableModel) tablecustomer.getModel();
        DefaultTableModel productModel = (DefaultTableModel) tableproduct.getModel();
        try {
            Connection con = connectionprovider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from customer");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("customer_pk"), rs.getString("name"), rs.getString("mobilenumber"), rs.getString("email")});

            }
            rs = st.executeQuery("select * from product inner join catagory on product .catagory_fk = catagory.catagory_pk");
            while (rs.next()) {
                productModel.addRow(new Object[]{rs.getString("product_pk"), rs.getString("name"), rs.getString("price"), rs.getString("quantity"), rs.getString("description"), rs.getString("catagory_fk"), rs.getString(8)});
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_formComponentShown

    private void txtcustomernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomernameActionPerformed

    private void txtproductnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductnameActionPerformed

    private void txtproductdescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductdescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductdescriptionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String noofunits = txtorderquantity.getText();
        if (!noofunits.equals("")) {
            String productname = txtproductname.getText();
            String productdescription = txtproductdescription.getText();
            String productprice = txtproductprice.getText();

            int totalprice = Integer.parseInt(txtorderquantity.getText()) * Integer.parseInt(productprice);
            int checkstock = 0;
            int checkproductalredyexistincart = 0;

            try {
                Connection con = connectionprovider.getCon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from product where product_pk=" + productpk + "");
                while (rs.next()) {
                    if (rs.getInt("quantity") >= Integer.parseInt(noofunits)) {
                        checkstock = 1;
                    } else {
                        JOptionPane.showMessageDialog(null, "product is out of stock only " + rs.getInt("quantity") + "Left");
                    }
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            if (checkstock == 1) {
                DefaultTableModel model = (DefaultTableModel) tablecart.getModel();
                if (tablecart.getRowCount() != 0) {
                    for (int i = 0; i < tablecart.getRowCount(); i++) {
                        if (Integer.parseInt(model.getValueAt(i, 0).toString()) == productpk) {
                            checkproductalredyexistincart = 1;
                            JOptionPane.showMessageDialog(null, "product alrady exist in cart");
                        }
                    }

                }
                if (checkproductalredyexistincart == 0) {
                    model.addRow(new Object[]{productpk, productname, noofunits, productprice, productdescription, totalprice});
                    finaltotalprice = finaltotalprice * totalprice;
                    lblfinaltotalprice.setText(String.valueOf(finaltotalprice));
                    JOptionPane.showMessageDialog(null, "Added successfully");
                }
                clearproductfields();
            }
        } else {
            JOptionPane.showMessageDialog(null, "number of quantity and product feild is required");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtorderquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorderquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorderquantityActionPerformed

    private void btnsaveorderdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveorderdetailsActionPerformed
        // TODO add your handling code here:
        if (finaltotalprice != 0 && !txtcustomername.getText().equals("")) {
            orderid = getUniqueID("bill");
            DefaultTableModel dtm = (DefaultTableModel) tablecart.getModel();
            if (tablecart.getRowCount() != 0) {
                for (int i = 0; i < tablecart.getRowCount(); i++) {
                    try {
                        Connection con = connectionprovider.getCon();
                        Statement st = con.createStatement();
                        st.executeUpdate("Update product set quantitiy=quantity-" + Integer.parseInt(dtm.getValueAt(i, 2).toString()) + "  where product_pk=" + Integer.parseInt(dtm.getValueAt(i, 0).toString()));
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
            try {
                SimpleDateFormat myformat = new SimpleDateFormat("dd-mm-yyyy");
                Calendar cal = Calendar.getInstance();
                Connection con = connectionprovider.getCon();
                PreparedStatement ps = con.prepareStatement("insert into orderdetail(orderid,customer_fk,orderdate,totalpaid)values(?,?,?,?)");
                ps.setString(1, orderid);
                ps.setInt(2, customerpk);
                ps.setString(3, myformat.format(cal.getTime()));
                ps.setInt(4, finaltotalprice);
                ps.executeUpdate();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            //creating document
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try {
                SimpleDateFormat myformat = new SimpleDateFormat("dd-mm-yyyy");
                Calendar cal = Calendar.getInstance();
                
                PdfWriter.getInstance(doc, new FileOutputStream(inventoryutils.billpath + "" + orderid + ".pdf"));
                doc.open();
                Paragraph projectname = new Paragraph("                                                            Inventory Management System\n");
                doc.add(projectname);
                Paragraph StarLine = new Paragraph("********************************************************************************************************************");
                doc.add(StarLine);
                Paragraph details = new Paragraph("\tOrder ID:  " + orderid + "\nDate:  " + myformat.format(cal.getTime()) + "\nTotal Paid:  " + finaltotalprice);
                doc.add(details);
                doc.add(StarLine);
                PdfPTable tbl = new PdfPTable(5);
                PdfPCell nameCell = new PdfPCell(new Phrase("name"));
                PdfPCell descriptionCell = new PdfPCell(new Phrase("description"));
                PdfPCell priceCell = new PdfPCell(new Phrase("price per unit"));
                PdfPCell quantityCell = new PdfPCell(new Phrase("quantity"));
                PdfPCell subtotalpriceCell = new PdfPCell(new Phrase("sub total price"));
                BaseColor backgroundColor = new BaseColor(255, 204, 51);
                nameCell.setBackgroundColor(backgroundColor);
                descriptionCell.setBackgroundColor(backgroundColor);
                priceCell.setBackgroundColor(backgroundColor);
                quantityCell.setBackgroundColor(backgroundColor);
                subtotalpriceCell.setBackgroundColor(backgroundColor);

                tbl.addCell(nameCell);
                tbl.addCell(descriptionCell);
                tbl.addCell(priceCell);
                tbl.addCell(quantityCell);
                tbl.addCell(subtotalpriceCell);

                for (int i = 0; i < tablecart.getRowCount(); i++) {
                    tbl.addCell(tablecart.getValueAt(i, 1).toString());
                    tbl.addCell(tablecart.getValueAt(i, 4).toString());
                    tbl.addCell(tablecart.getValueAt(i, 3).toString());
                    tbl.addCell(tablecart.getValueAt(i, 2).toString());
                    tbl.addCell(tablecart.getValueAt(i, 5).toString());

                }
                doc.add(tbl);
                doc.add(StarLine);
              Paragraph thanksMsg = new Paragraph("Thank you Please Visit again.");
              doc.add(thanksMsg);
              openpdf.openbyId(orderid);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            doc.close();
            setVisible(false);
            new manageorder().setVisible(true);
            
        }
        else{
         JOptionPane.showMessageDialog(null,"Please add some product to cart or select customer");
        }

    }//GEN-LAST:event_btnsaveorderdetailsActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new manageorder().setVisible(true);
    }//GEN-LAST:event_btnresetActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tablecustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecustomerMouseClicked
        // TODO add your handling code here:
        int index = tablecustomer.getSelectedRow();
        TableModel model = tablecustomer.getModel();
        String id = model.getValueAt(index, 0).toString();
        customerpk = Integer.parseInt(id);
        String name = model.getValueAt(index, 1).toString();
        txtcustomername.setText(name);
        String mobilenumber = model.getValueAt(index, 2).toString();
        txtcustomermobilenumber.setText(mobilenumber);
        String email = model.getValueAt(index, 3).toString();
        txtcustomeremail.setText(email);
    }//GEN-LAST:event_tablecustomerMouseClicked

    private void tableproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproductMouseClicked
        // TODO add your handling code here:
        int index = tableproduct.getSelectedRow();
        TableModel model = tableproduct.getModel();
        String id = model.getValueAt(index, 0).toString();
        productpk = Integer.parseInt(id);
        String productname = model.getValueAt(index, 1).toString();
        txtproductname.setText(productname);
        String productprice = model.getValueAt(index, 2).toString();
        txtproductprice.setText(productprice);
        String productdescription = model.getValueAt(index, 4).toString();
        txtproductdescription.setText(productdescription);
    }//GEN-LAST:event_tableproductMouseClicked

    private void tablecartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecartMouseClicked
        // TODO add your handling code here:

        int index = tablecart.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete remove this product", "select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            TableModel model = tablecart.getModel();
            String subtotal = model.getValueAt(index, 5).toString();
            finaltotalprice = finaltotalprice - Integer.parseInt(subtotal);
            lblfinaltotalprice.setText(String.valueOf(finaltotalprice));
            ((DefaultTableModel) tablecart.getModel()).removeRow(index);

        }

    }//GEN-LAST:event_tablecartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsaveorderdetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblfinaltotalprice;
    private javax.swing.JTable tablecart;
    private javax.swing.JTable tablecustomer;
    private javax.swing.JTable tableproduct;
    private javax.swing.JTextField txtcustomeremail;
    private javax.swing.JTextField txtcustomermobilenumber;
    private javax.swing.JTextField txtcustomername;
    private javax.swing.JTextField txtorderquantity;
    private javax.swing.JTextField txtproductdescription;
    private javax.swing.JTextField txtproductname;
    private javax.swing.JTextField txtproductprice;
    // End of variables declaration//GEN-END:variables
}
